name: auralab
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.7
  http: ^1.1.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  audioplayers: ^6.0.0
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

